[package]
name = "rhosts"
version = "0.0.1"
authors = ["Steven Black <steveb@stevenblack.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
futures = "0.3"
addr = "0.15.3"